### ISSUE TITLE
FINALE: End screen/overlay...

### ISSUE THREAD

**Issue by Option4Studios** [Option4Studios/Custard#102]
You truly are a master of creating desserts.

Beat your scores and see if you are the world's greatest by checking out the Game Center leaderboard.

**Comment by Rich-Option4Studios** [comment]
![custard_designs_v2_0_game completed](https://cloud.githubusercontent.com/assets/11824245/13034921/4ef0dad2-d33a-11e5-8252-5e745348d132.png)
