### ISSUE TITLE
TILE: Create candle tile

### ISSUE THREAD

**Issue by Rich-Option4Studios** [Option4Studios/Custard#109]

**Comment by Rich-Option4Studios** [comment]
![capture](https://cloud.githubusercontent.com/assets/11824245/13202874/cbcfc296-d8a0-11e5-946b-3569b65eb888.JPG)

**Comment by Rich-Option4Studios** [comment]
Gameplay spritesheet updated in Dropbox. It's in 3 parts, flame, candle and stripes

**Comment by Option4Studios** [comment]
need to stop white circle going colour of layer special colour!

**Comment by Option4Studios** [comment]
fixed - reset to white....
