### ISSUE TITLE
TIP OVERLAY IN TUTORIAL

### ISSUE THREAD

**Issue by Option4Studios** [Option4Studios/Custard#110]

**Comment by Rich-Option4Studios** [comment]
![custard_designs_v2_0_07_howtoplay](https://cloud.githubusercontent.com/assets/11824245/13206197/141b6fd2-d8f1-11e5-83fd-ac69f44f1630.png)
![custard_designs_v2_0_tips](https://cloud.githubusercontent.com/assets/11824245/13206199/1ffbca4a-d8f1-11e5-8f71-cc1e6d71c8ab.png)

**Comment by Rich-Option4Studios** [comment]
I wonder if we can use 9 slice scaling as we have quite a few frames now.

http://www.unityrealm.com/unity-9-slice-advantages/

**Comment by Option4Studios** [comment]
tried 9 slice, but didn't work so well on dashed line! used tiled instead...?!
