### ISSUE TITLE
END TUTORIAL SCREEN: logo or 'custard'

### ISSUE THREAD

**Issue by Option4Studios** [Option4Studios/Custard#146]

**Comment by Rich-Option4Studios** [comment]
![custard_tutorial-11](https://cloud.githubusercontent.com/assets/11824245/13548631/aa4cd040-e2ec-11e5-9bc7-56b829708741.png)

An idea is to include the tootips in the tutorial so the style of the tips in the game don't come out of the blue.

**Comment by Rich-Option4Studios** [comment]
Logo is here

https://www.dropbox.com/s/txqdu8faexc50uw/custard_logo_rgb.png?dl=0

**Comment by Option4Studios** [comment]
all done rough... need to think about fading all at once.... and tidying animation rates etc...

**Comment by Option4Studios** [comment]
Done. Need to tweak timings of tutorial elements.
