### ISSUE TITLE
GAME: remove 'custard' and replace with goal tiles

### ISSUE THREAD

**Issue by Option4Studios** [Option4Studios/Custard#153]

**Comment by Rich-Option4Studios** [comment]
![custard_designs_v2_0_05_gameplay](https://cloud.githubusercontent.com/assets/11824245/13530205/1a7d6440-e218-11e5-8109-afbbeea9b5c8.png)

**Comment by Rich-Option4Studios** [comment]
I've moved the trophy to the right of the score to help when it grows...
