### ISSUE TITLE
MENU MESSAGE & HINTS:

### ISSUE THREAD

**Issue by Option4Studios** [Option4Studios/Custard#158]
- [ ] Tailed box to replace menu message
- [ ] tailed boxes and middle 'box with tick' for hints:
    - [ ] level 1 - timer and gather button
    - [ ] level 2 - high score and [new] goal tiles (top)

**Comment by Rich-Option4Studios** [comment]
![custard_tutorial-10](https://cloud.githubusercontent.com/assets/11824245/13541398/d0bf7884-e253-11e5-9269-bdd4e74707b2.png)
![custard_tutorial2-10](https://cloud.githubusercontent.com/assets/11824245/13541399/d0c4823e-e253-11e5-865d-3ec5036b1b6b.png)

**Comment by Rich-Option4Studios** [comment]
![custard_designs_v2_0_03_desserts menu](https://cloud.githubusercontent.com/assets/11824245/13541409/e007bb94-e253-11e5-9e88-03d4fb4fd5cd.png)
