### ISSUE TITLE
COLOUR BLINDNESS: Add small colour initials to tiles if select an option in settings?

### ISSUE THREAD

**Issue by Rich-Option4Studios** [Option4Studios/Custard#161]

**Comment by Option4Studios** [comment]
Added functionality to show text at top of tile - TextMesh 'cb', with new var in GSM
Texts in content.csv

Need to design the toggle in settings, if we're going to use it :O)

**Comment by Rich-Option4Studios** [comment]
![custard_designs_v2_0_08_settings](https://cloud.githubusercontent.com/assets/11824245/13548113/08bfd8f0-e2e0-11e5-8c32-86587b2d803b.png)

Made notification toggles smaller to accomodate the extra toggle.

Also made the delete data button less attention seeking.

**Comment by Rich-Option4Studios** [comment]
New plan, we now recolour pink to a darker shade for the colour blind option.

Pink : #d08e8e or RGB(208,142,142)
Dark Pink: #b76568 or RGB(183, 101, 104)
