### ISSUE TITLE
REMOVE ADS: grey outline and text "ads removed" - instead of 'nothing there'?

### ISSUE THREAD

**Issue by Option4Studios** [Option4Studios/Custard#162]

**Comment by Rich-Option4Studios** [comment]
![custard_designs_v2_0b_08_settings](https://cloud.githubusercontent.com/assets/11824245/13547917/f876187e-e2da-11e5-82fe-5a455133cb6b.png)

**Comment by Rich-Option4Studios** [comment]
remove-button-border.png added to UI spritesheet

**Comment by Rich-Option4Studios** [comment]
I think last time I tested this, I bought the IAP but the ads removed wasn't updated until I left the screen. Probably needs to update the image on a IAP callback

**Comment by Rich-Option4Studios** [comment]
Also applies to issue [#166]
