### ISSUE TITLE
Tips, first 3 - images?!

### ISSUE THREAD

**Issue by Option4Studios** [Option4Studios/Custard#167]
Custard level 4, 8 and jelly 1

**Comment by Rich-Option4Studios** [comment]
![custard_tutorial01-12](https://cloud.githubusercontent.com/assets/11824245/13642972/9b70220c-e616-11e5-86ce-36b9f69c414b.png)

**Comment by Rich-Option4Studios** [comment]
![custard_tutorial02-12](https://cloud.githubusercontent.com/assets/11824245/13642976/a1570b04-e616-11e5-8dbe-e57eaa9cd0b1.png)

**Comment by Rich-Option4Studios** [comment]
![custard_tutorial03-12](https://cloud.githubusercontent.com/assets/11824245/13642983/a7a5973c-e616-11e5-8b02-af1d7e8502aa.png)

**Comment by Rich-Option4Studios** [comment]
![custard_tutorial04-12](https://cloud.githubusercontent.com/assets/11824245/13642991/af85b31a-e616-11e5-9523-f4169e6528de.png)

**Comment by Rich-Option4Studios** [comment]
![custard_tutorial05-12](https://cloud.githubusercontent.com/assets/11824245/13642998/b5139428-e616-11e5-86e8-b80c386e04fa.png)

**Comment by Rich-Option4Studios** [comment]
@Option4Studios what do we think to these and the additional tips?
