### ISSUE TITLE
TIPS

### ISSUE THREAD

**Issue by Option4Studios** [Option4Studios/Custard#17]

**Comment by Rich-Option4Studios** [comment]
![custard_tutorial_tipextras](https://cloud.githubusercontent.com/assets/11824245/11460392/97b51ba4-96e3-11e5-9b28-7657e1537760.png)
![custard_tutorial_tiplayers](https://cloud.githubusercontent.com/assets/11824245/11460393/97d1a5bc-96e3-11e5-85cb-0bf2806296f7.png)

**Comment by Rich-Option4Studios** [comment]
Added a frames spritesheet in Dropbox
