### ISSUE TITLE
Overlays: Enable/Disable when required

### ISSUE THREAD

**Issue by Rich-Option4Studios** [Option4Studios/Custard#171]
Using the Frame Debugger, when panels/overlays not visible are disabled (in the inspector), the draw calls go down.

Examples

Menu > Disable goalPanel, RemoveAdsPanel

Goal Panel > Disable menuPanel, removeAdsPanel

Settings Panel (start + menu)  > Disable goalPanel, CreditsPanel, DeleteDataPanel, DebugPanel

During Tutorial > Disable TutorialPanel

During a game/level > Disable pauseGamePanel, tipPanel, megaBonus (not if it causes  problems), goalReached (ditto)

**Comment by Rich-Option4Studios** [comment]
Actually, setting the Canvas Group Alpha to 0 of a panel also reduces DrawCalls and maybe less expensive than disabling a panel

**Comment by Rich-Option4Studios** [comment]
Needs another iteration to make this functionality more solid. Instances of overlays disappearing and leaving a white overlay

**Comment by Option4Studios** [comment]
tutorials - check all hiding and showing (like settings)!
