### ISSUE TITLE
OVERLAY: Block buttons under Settings overlay e.g Start screen buttons

### ISSUE THREAD

**Issue by Rich-Option4Studios** [Option4Studios/Custard#40]
If you open the settings on the Start screen, you can click between the settings buttons and select a Start screen button instead, like the Tutorials button.

**Comment by Option4Studios** [comment]
also in the game - settings overlay

**Comment by Rich-Option4Studios** [comment]
99% there. Weirdly on the first time you open the settings while playing, you can move a tile but not after that unless you play the level again.

I would say this is a low priority bug now.

**Comment by Option4Studios** [comment]
fixed - tileswitch var not set to false
