### ISSUE TITLE
CREDITS: credits screen and links on settings screen

### ISSUE THREAD

**Issue by Rich-Option4Studios** [Option4Studios/Custard#49]

**Comment by Option4Studios** [comment]
![custard_prototypev2_0_08_settings](https://cloud.githubusercontent.com/assets/11822462/12987369/b130cd86-d0f3-11e5-84ae-013e8db72640.png)
![custard_prototypev2_0_credits](https://cloud.githubusercontent.com/assets/11822462/12987376/ba187886-d0f3-11e5-9705-bd9507b00793.png)
