### ISSUE TITLE
SFX

### ISSUE THREAD

**Issue by Option4Studios** [Option4Studios/Custard#51]

**Comment by Option4Studios** [comment]
- [ ] When reach the goal (to go alongside the banner)
- [ ] When tiles slide off
- [ ] When mixing bowl turning

**Comment by Rich-Option4Studios** [comment]
[gameplay-02.zip](https://github.com/Option4Studios/Custard/files/139694/gameplay-02.zip)

Unzip this short video to see the timing of the banner sliding in and out with the audio
