### ISSUE TITLE
Goal Screen animation

### ISSUE THREAD

**Issue by Option4Studios** [Option4Studios/Custard#54]
1. tiles come in one at a time
2. target bounces in
3. play button fades in

**Comment by Rich-Option4Studios** [comment]
Nearly there. Might need a few subtle tweaks. As with any text bouncing in, the target number doesn't look quite right.

**Comment by Rich-Option4Studios** [comment]
BUG: Whoops, if you hit back while the target text animates in, it remains on screen on the menu.

**Comment by Rich-Option4Studios** [comment]
The text on the tiles and target score is jagged. I think this is the scale problem where we scale the z depth
