### ISSUE TITLE
Settings overlay:

### ISSUE THREAD

**Issue by Option4Studios** [Option4Studios/Custard#61]
- [x] should be able to select anywhere on notification/SFX toggle to switch
- [x] 'Off' on SFX cut off at start?!

**Comment by Option4Studios** [comment]
'Off' cannot replicate on editor, but have increased size of bounds

**Comment by Rich-Option4Studios** [comment]
Sadly, the Off text is even worse. Cuts off badly on SFX and Notifications. Wonder if it's a z depth issue.
