### ISSUE TITLE
Overlays:

### ISSUE THREAD

**Issue by Option4Studios** [Option4Studios/Custard#63]
first level overlays back button not always working and can cause a white screen if double click/go mad...

**Comment by Rich-Option4Studios** [comment]
Don't know if this was ready for testing as I accidentally cleared the Testing column.

Ingame > Settings : Hitting the back button repeatedly on settings is fine
 Ingame> Pause> How To Play: Hammering the back button causes the game screen to lose the top UI and the gather button.
Start > How To Play> Basics: Hammering the back button reveals white screen

**Comment by Option4Studios** [comment]
fixed :O)
