### ISSUE TITLE
Menu:

### ISSUE THREAD

**Issue by Option4Studios** [Option4Studios/Custard#66]
- [x] remove bounce on higher score animation...
- [x] remove trophy and add title overall score above (smaller) = center
- [x] make sure no grey under ickle tiles!
- [x] check when 'new high score' animation happens!

**Comment by Option4Studios** [comment]
last checkbox = was reading achievement high score rather than overall score!

**Comment by Rich-Option4Studios** [comment]
I think the overall high score stopped animating after so many levels

**Comment by Option4Studios** [comment]
CANNOT REPLICATE
