### ISSUE TITLE
Colour trophy for overall score on Menu

### ISSUE THREAD

**Issue by Option4Studios** [Option4Studios/Custard#67]

**Comment by Rich-Option4Studios** [comment]
![custard_designs_v2_0_03_desserts menu](https://cloud.githubusercontent.com/assets/11824245/12378745/da6de034-bd3f-11e5-937f-26dab091cb4e.png)

**Comment by Rich-Option4Studios** [comment]
![custard_designs_v2_0_03_desserts menu](https://cloud.githubusercontent.com/assets/11824245/12378748/1312d502-bd40-11e5-827d-8f4886bfb460.png)

**Comment by Rich-Option4Studios** [comment]
Like you said @Option4Studios , probably too busy to have a box. However, I've played with the layout and made the trophy into a small yellow one.

**Comment by Option4Studios** [comment]
Use big trophy in spritesheet - resize and re-colour

**Comment by Option4Studios** [comment]
The blue means when the sprite colour is set to yellow, it turns green...
A white trophy is needed, or the colour changed, to re-colour to the correct yellow

**Comment by Rich-Option4Studios** [comment]
UI sprite sheet updated Dropbox\Custard\Design\ExportedAssets\Spritesheets\HD\

The original menu trophy has been changed to white
