### ISSUE TITLE
Wiggly line on tips and messages?

### ISSUE THREAD

**Issue by Option4Studios** [Option4Studios/Custard#75]

**Comment by Rich-Option4Studios** [comment]
![custard_tutorial_tiplayers](https://cloud.githubusercontent.com/assets/11824245/12378602/ecf613c0-bd3a-11e5-8536-0fab9a9ff0bb.png)

**Comment by Rich-Option4Studios** [comment]
Do we like this?

**Comment by Rich-Option4Studios** [comment]
![custard_tutorial_tiplayers](https://cloud.githubusercontent.com/assets/11824245/12378722/f6945b68-bd3e-11e5-9d44-1d7f8801384a.png)

**Comment by Rich-Option4Studios** [comment]
Alternatively, we could have the line of tiles

**Comment by Option4Studios** [comment]
Add wavey line
