### ISSUE TITLE
SAVE DATA: Delete save data screen

### ISSUE THREAD

**Issue by Rich-Option4Studios** [Option4Studios/Custard#78]

**Comment by Rich-Option4Studios** [comment]
![custard_designs_v2_0_message](https://cloud.githubusercontent.com/assets/11824245/12378637/31c827b2-bd3c-11e5-83c7-ad6b7f2085e9.png)

**Comment by Rich-Option4Studios** [comment]
Effectively 'Delete Sava Data' or reset the game

**Comment by Option4Studios** [comment]
Make sure this is above z depth (clashing with overlay below)
