### ISSUE TITLE
IN GAME:  Reached goal banner

### ISSUE THREAD

**Issue by Rich-Option4Studios** [Option4Studios/Custard#80]

**Comment by Rich-Option4Studios** [comment]
![custard_designs_v2_0_11_groupednotifications](https://cloud.githubusercontent.com/assets/11824245/12547642/688d86e4-c349-11e5-8a0f-07c7aac9e49f.png)

**Comment by Rich-Option4Studios** [comment]
Main rectangle = 1536 x 340 px
Rectangle underneath = 1536 x 17px

**Comment by Rich-Option4Studios** [comment]
We must be able to recreate this in a optimal way e.g do we need a sprite just 10 x 340px, set as point filtering and stretched to 1536px

**Comment by Option4Studios** [comment]
use plane
