### ISSUE TITLE
ADVERTS: When ad shows after completing/failing a level, it then doesn't let you see the end overlay

### ISSUE THREAD

**Issue by Rich-Option4Studios** [Option4Studios/Custard#84]
I need to see it again, but does the game/level end and then you see the advert before you see the 'you have failed/well done' overlay? However I'm sure I only saw the overlay for a split second.

Ideally perhaps the advert should show when you hit Dessert Menu or Replay?

**Comment by Option4Studios** [comment]
Nothing wrong with functionality, advert only shows when menu or retry button is selected. However, it does show the pass/failed screen briefly which i think caused confusion - have added a 'loading' panel to show over these when ad shows...
