### ISSUE TITLE
ADVERTS: Add message inviting to remove ads after first ad is shown?

### ISSUE THREAD

**Issue by Rich-Option4Studios** [Option4Studios/Custard#86]
Occasionally we show adverts,
which can be quite annoying.

For the price of a small mediocre coffee,
why not remove them for good?

**Comment by Option4Studios** [comment]
Design an overlay to show after the first ad has been shown - need variable so know has been seen and place in menu scene

**Comment by Rich-Option4Studios** [comment]
![custard_designs_v2_0_message](https://cloud.githubusercontent.com/assets/11824245/13034581/1a13cbfc-d331-11e5-9c63-369455938dda.png)

**Comment by Option4Studios** [comment]
Check all remove ads buttons everywhere
