### ISSUE TITLE
SETTINGS: Add Buttons

### ISSUE THREAD

**Issue by Option4Studios** [Option4Studios/Custard#96]
Twitter and like to icons?

Restore iCloud data
DESIGN:
- [x] Design and implement a button for cloud restore

BUILD
- [ ] implement button

Delete Data / Reset Game

DESIGN
- [x] cross for no button

BUILD
- [ ] message - are you sure?

**Comment by Rich-Option4Studios** [comment]
![custard_designs_v2_0_08_settings](https://cloud.githubusercontent.com/assets/11824245/13034342/8539b5a6-d32a-11e5-8164-b26e12fbc596.png)

**Comment by Rich-Option4Studios** [comment]
Twitter Blue: #4099FF Dark Blue: #1F6DAD
Facebook Blue: #3B5998 Dark Blue: #213C6D

**Comment by Rich-Option4Studios** [comment]
UI spriteshet updated on Dropbox

We will use the remove ads button as a restore button as well.
