### ISSUE TITLE
SWAP tiles: check merging as swap over

### ISSUE THREAD

**Issue by Option4Studios** [Option4Studios/Custard#99]
sprite.sortingOrder = sortingOrder;

**Comment by Rich-Option4Studios** [comment]
Tiles still look like they are merging?

**Comment by Rich-Option4Studios** [comment]
![untitled-2](https://cloud.githubusercontent.com/assets/11824245/13705784/4076b6ce-e79a-11e5-8cc9-5680c8a2e193.png)

**Comment by Rich-Option4Studios** [comment]
Perhaps hange the initial -8 z-depth of the tile to -10, for the tile you are moving. Then change it back to -8.

**Comment by Rich-Option4Studios** [comment]
![untitled-2](https://cloud.githubusercontent.com/assets/11824245/13706119/9a235a50-e79b-11e5-91a7-7ab52c09fc81.png)

**Comment by Rich-Option4Studios** [comment]
Weirdly with the above example, if you move the two identical tiles below it, they are fine.

**Comment by Rich-Option4Studios** [comment]
Perhaps hange the initial -8 z-depth of the whole tile to -10, for the tile you are moving. Then change it back to -8.
